YAPP-Github/21st-Android-Team-1-BE

src/main/java/yapp/buddycon/common/response/DefaultResponseDto.java
src/main/java/yapp/buddycon/web/coupon/adapter/in/CouponController.java
src/main/java/yapp/buddycon/web/coupon/adapter/in/SharedCouponController.java
src/main/java/yapp/buddycon/web/coupon/adapter/in/request/CouponStateRequestDto.java
src/main/java/yapp/buddycon/web/coupon/adapter/in/request/CustomCouponCreationRequestDto.java
src/main/java/yapp/buddycon/web/coupon/adapter/in/request/CustomCouponInfoRequestDto.java
src/main/java/yapp/buddycon/web/coupon/adapter/in/request/GifticonCreationRequestDto.java
src/main/java/yapp/buddycon/web/coupon/adapter/in/request/GifticonInfoRequestDto.java
src/main/java/yapp/buddycon/web/coupon/adapter/in/response/CouponsResponseDto.java
src/main/java/yapp/buddycon/web/coupon/adapter/in/response/CustomCouponInfoResponseDto.java
src/main/java/yapp/buddycon/web/coupon/adapter/in/response/GifticonInfoResponseDto.java
src/main/java/yapp/buddycon/web/coupon/adapter/in/response/SharedCouponsResponseDto.java
src/main/java/yapp/buddycon/web/coupon/adapter/out/CouponJpaRepository.java

coupon 도메인의 mock api 추가
- DefaultResponseDto를 common의 response 패키지에 추가하였습니다.
- success 여부, message 값을 전달합니다. (Post, Put, Patch, Delete등 command요청에서 주로 사용하였습니다.)
- coupon 도메인의 mock api를 추가하였습니다.
- controller의 코드가 길어져 앞으로 코드가 추가되면 가독성이 안좋아질 듯 합니다.. 추후 클래스 분리를 고려해 봐도 좋을것같습니다
x
close #9

[Issue #9] Swagger Mock API 추가 - Coupon

---

src/main/java/yapp/buddycon/web/auth/adapter/in/LoginController.java
src/main/java/yapp/buddycon/web/member/adapter/in/MemberController.java
src/main/java/yapp/buddycon/web/member/adapter/in/request/NotificationSettingUpdateRequestDto.java
src/main/java/yapp/buddycon/web/member/adapter/in/response/NotificationSettingResponseDto.java
src/main/java/yapp/buddycon/web/member/domain/NotificationSetting.java

Member, NotificationSetting 관련 목업 코드 추가
- NotificationSetting 엔티티 추가
- `GET::/api/v1/member/notification-setting`, `PUT::/api/v1/member/notification-setting` API 추가
- NotificationSettingResponseDto, NotificationSettingUpdateRequestDto 추가
notification 패키지와 member 패키지 사이에서 고민하다가 
회원가입 시 같이 생성되는 데이터라는 점과 로그인한 유저의 데이터를 가져온다는 점에서 member 안에 귀속되어 있는 정보라고 생각되어 member로 정했습니다!
close #12 
resolve #12

[issue #12] Swagger Mock API 추가 - Member, NotificationSetting

---

src/main/java/yapp/buddycon/common/PagingDto.java
src/main/java/yapp/buddycon/web/notification/adapter/in/NotificationController.java
src/main/java/yapp/buddycon/web/notification/adapter/in/response/NotificationResponseDto.java
src/main/java/yapp/buddycon/web/notification/adapter/out/NotificationJpaRepository.java
src/main/java/yapp/buddycon/web/notification/domain/Notification.java

Notification 관련 목업 코드 추가
- Notification 엔티티 추가
- `/api/v1/notification` API 추가
- NotificationResponseDto 추가
- 범용으로 사용할 PagingDto 추가
common에 PagingDto를 추가했습니다. 목록 조회 시 해당 클래스를 extend 해서 사용하면 좋을 듯 합니다.
close #10 
resolved #10

[issue #10] Swagger Mock API 추가 Notification

---

src/main/java/yapp/buddycon/web/member/domain/Member.java

멤버 엔티티 컬럼 추가
카카오로부터 받아오는 멤버의 이메일, 닉네임, 성별, 연령을 멤버 entity에 추가하였습니다
close #25

[Issue #25] 멤버 엔티티 컬럼 추가

---

src/main/java/yapp/buddycon/web/auth/adapter/in/LoginController.java
src/main/java/yapp/buddycon/web/auth/adapter/in/request/KakaoInfoRequestDto.java
src/main/java/yapp/buddycon/web/auth/application/port/in/AuthUseCase.java
src/main/java/yapp/buddycon/web/auth/application/port/in/OAuthMemberInfo.java
src/main/java/yapp/buddycon/web/auth/application/service/AuthService.java
src/main/java/yapp/buddycon/web/auth/application/service/KakaoOAuthMapper.java
src/main/java/yapp/buddycon/web/member/domain/Member.java

Kakao oauth token 로직의 request 형식 변경
멤버의 카카오 정보(이메일, 닉네임, 성별, 연령대)를 프론트 측에서 보내주시고 있기 때문에, 그에 맞춰 request 형식을 변경하였습니다.
close #24

[Issue #24] Kakao oauth token 로직의 request 형식 변경

---

src/main/java/yapp/buddycon/web/coupon/adapter/in/CouponController.java
src/main/java/yapp/buddycon/web/coupon/adapter/in/response/CustomCouponInfoResponseDto.java
src/main/java/yapp/buddycon/web/coupon/adapter/in/response/GifticonInfoResponseDto.java
src/main/java/yapp/buddycon/web/coupon/adapter/out/CouponJpaRepository.java
src/main/java/yapp/buddycon/web/coupon/adapter/out/CouponQueryRepository.java
src/main/java/yapp/buddycon/web/coupon/application/port/in/CouponUseCase.java
src/main/java/yapp/buddycon/web/coupon/application/port/out/CouponQueryPort.java
src/main/java/yapp/buddycon/web/coupon/application/service/CouponService.java

기프티콘, 제작티콘의 상세 조회 api 구현
|기프티콘 상세화면|제작티콘 상세화면|
|---|---|
|<img width="400" alt="스크린샷 2023-01-27 오후 7 19 25" src="https://user-images.githubusercontent.com/69676101/215062846-7d89501b-d76f-467e-a660-b277ee0a0b45.png">|<img width="400" alt="스크린샷 2023-01-27 오후 7 20 37" src="https://user-images.githubusercontent.com/69676101/215063074-8a6b6951-f331-407c-a872-67ee928c975d.png">|
- 기프티콘, 제작티콘의 상세 조회 api를 구현하였습니다.
- id가 pathvariable로 받아온 id와 동일하며, memberId가 authmember id와 동일한 쿠폰을 반환합니다.
close #32

[Issue #32] 쿠폰 상세 조회

---

src/main/java/yapp/buddycon/common/exception/ErrorCode.java
src/main/java/yapp/buddycon/web/coupon/adapter/in/CouponController.java
src/main/java/yapp/buddycon/web/coupon/adapter/in/response/CouponsResponseDto.java
src/main/java/yapp/buddycon/web/coupon/adapter/out/CouponJpaRepository.java
src/main/java/yapp/buddycon/web/coupon/adapter/out/CouponQueryRepository.java
src/main/java/yapp/buddycon/web/coupon/application/port/in/CouponUseCase.java
src/main/java/yapp/buddycon/web/coupon/application/port/out/CouponQueryPort.java
src/main/java/yapp/buddycon/web/coupon/application/service/CouponService.java
src/main/java/yapp/buddycon/web/coupon/application/service/SortPageableValidation.java

기프티콘, 제작티콘의 쿠폰 정렬 조회 api 구현
- page 처리를 통해 위 화면에 해당하는 api를 구현하였습니다.
- pageable의 sort에서는 entity의 embedded내부 속성을 불러들이지 못하는걸로 보입니다.
- 따라서 현재 embedded내부 필드(name, expireDate)의 Pageable 요청 포맷은
- page=3&size=10&sort=couponInfo.expireDate,DESC
- 와 같이 embedded클래스의 이름(couponInfo)을 포함하여 요청해야합니다.
- 구글링을 아무리해봐도 나오는 정보가 그다지 없어서 우선 위와같은 포맷으로 프론트분들께 요청드리려 합니다.
- 혹시 현희님 이부분에 대해 알고계신다면ㅜㅜ 리뷰 부탁드립니다.
close #28

[Issue #28] 쿠폰 정렬 조회

---

src/main/java/yapp/buddycon/common/exception/ErrorCode.java
src/main/java/yapp/buddycon/web/coupon/domain/Coupon.java
src/main/java/yapp/buddycon/web/coupon/domain/CouponInfo.java
src/main/java/yapp/buddycon/web/notification/adapter/in/NotificationController.java
src/main/java/yapp/buddycon/web/notification/adapter/in/response/NotificationResponseDto.java
src/main/java/yapp/buddycon/web/notification/adapter/out/NotificationQueryRepository.java
src/main/java/yapp/buddycon/web/notification/application/port/in/NotificationUseCase.java
src/main/java/yapp/buddycon/web/notification/application/port/out/NotificationQueryPort.java
src/main/java/yapp/buddycon/web/notification/application/service/NotificationService.java
src/main/java/yapp/buddycon/web/notification/domain/Notification.java

알림 상세 조회 API 추가
- 알림이나 공지사항 내용을 상세 조회하는 api를 구현했습니다.
- 공지사항의 경우 member와 coupon이 null이기 때문에 알림 id만 받고, 권한을 확인하는 방식을 사용했습니다.
- 공지사항 : `member == null, coupon == null`
- 알림 : `member != null, coupon != null`
- JPQL을 쓰지 않는 방법을 사용해 봤습니다. 의견 부탁드립니다! (JPQL 쓰는게 더 깔끔한 것 같기도 합니다 흠흠,,)

[Issue #16] 알림 상세 조회 API 추가

---

src/main/java/yapp/buddycon/common/exception/ErrorCode.java
src/main/java/yapp/buddycon/common/exception/GlobalExceptionHandler.java
src/main/java/yapp/buddycon/web/coupon/adapter/in/CouponController.java
src/main/java/yapp/buddycon/web/coupon/adapter/in/response/SharedCustomCouponResponseDto.java
src/main/java/yapp/buddycon/web/coupon/adapter/in/response/SharedGifticonInfoResponseDto.java
src/main/java/yapp/buddycon/web/coupon/adapter/out/SharedCouponJpaRepository.java
src/main/java/yapp/buddycon/web/coupon/adapter/out/SharedCouponQueryRepository.java
src/main/java/yapp/buddycon/web/coupon/application/port/in/CouponUseCase.java
src/main/java/yapp/buddycon/web/coupon/application/port/out/CouponToSharedCouponQueryPort.java
src/main/java/yapp/buddycon/web/coupon/application/service/CouponService.java
src/main/java/yapp/buddycon/web/coupon/domain/SharedCouponInfo.java

바코드로 쿠폰 정보 불러오기 api
- ShareCouponInfo 클래스 내에 memberId가 OneToOne 으로 매핑 되어있지 않았어서, 리팩토링하였습니다.
- global handler에 메소드를 추가하였습니다 (현희님 어떻게 생각하실지 궁금합니다..)
- 바코드를 불러올때 해당하는 SharedCoupon의 튜플이 두개 이상이라면 'query did not return a unique result: 2' Exception이 발생하였습니다.
- 제가 생각한 해결방안은 아래와 같았습니다
1. List로 받아와서 그 중 하나를 선택하거나
2. query에 limit 1을 걸거나
3. internal server error로 exception을 냄
- 제가 생각했을 때, 1번과 2번은 사용자에게 잘못된 쿠폰정보가 내려갈 수도 있을 것같아서, 3번을 선택했습니다.
- 3번을 택한 대신, 프론트 분들께 대략적으로 어떤 exception인지 전달드려야 할 것같아, PersistenceException을 Handling하도록 메소드를 추가하였습니다.
- 대신 너무 자세한 서버의 상황은 노출되지 않도록, database exception이라는 메시지를 전달드리는 것으로 구현하였습니다.
- 바코드로 쿠폰 정보 불러오기 api를 구현하였습니다!
close #37

[Issue #37] 바코드로 쿠폰 정보 불러오기 api

---

src/main/java/yapp/buddycon/web/coupon/adapter/in/SharedCouponController.java
src/main/java/yapp/buddycon/web/coupon/adapter/in/response/SharedCouponsResponseDto.java
src/main/java/yapp/buddycon/web/coupon/adapter/out/SharedCouponJpaRepository.java
src/main/java/yapp/buddycon/web/coupon/adapter/out/SharedCouponQueryRepository.java
src/main/java/yapp/buddycon/web/coupon/application/port/in/SharedCouponUseCase.java
src/main/java/yapp/buddycon/web/coupon/application/port/out/SharedCouponQueryPort.java
src/main/java/yapp/buddycon/web/coupon/application/service/SharedCouponService.java
src/main/java/yapp/buddycon/web/coupon/application/service/SortPageableValidation.java

만든 쿠폰 정렬 조회 api 구현
만든 쿠폰 정렬 조회 api 구현 완료
- 만든 쿠폰 정렬 조회
- request로 unshared(boolean), pageable(Pageable)을 받아옴
- 미공유순인경우 (unshared == true)
```java   
@Query(value = """
select new yapp.buddycon.web.coupon.adapter.in.response.SharedCouponsResponseDto(s.id, s.sharedCouponInfo.imageUrl, s.sharedCouponInfo.name, s.sharedCouponInfo.expireDate, s.shared)
from SharedCoupon s
where s.sharedCouponInfo.sentMember.id = :memberId
order by s.shared
""")
List<SharedCouponsResponseDto> findUnsharedCustomCouponsSortedBy(Long memberId, Pageable pageable);
```
- shared로 order후 createdAt 내림차순 정렬하는 쿼리
- 유효일자순,만든순,이름순의 경우 (unshared == false)
- pageable을 토대로 정렬
close #42

[Issue #42] 만든 쿠폰 정렬 조회 api

---

src/main/java/yapp/buddycon/common/PagingDto.java
src/main/java/yapp/buddycon/common/exception/ErrorCode.java
src/main/java/yapp/buddycon/web/notification/adapter/in/NotificationController.java
src/main/java/yapp/buddycon/web/notification/adapter/out/NotificationJpaRepository.java
src/main/java/yapp/buddycon/web/notification/adapter/out/NotificationQueryRepository.java
src/main/java/yapp/buddycon/web/notification/application/port/in/NotificationUseCase.java
src/main/java/yapp/buddycon/web/notification/application/port/out/NotificationQueryPort.java
src/main/java/yapp/buddycon/web/notification/application/service/NotificationService.java
src/main/java/yapp/buddycon/web/notification/domain/Notification.java

알림 목록 조회 및 확인 완료 처리 API 추가
- PagingDto 추가
- `GET::/api/v1/notifications` API 추가
- 공지사항도 member 별로 각각 따로 가져야 할 것 같아서 엔티티를 변경하였습니다. 우선 가장 간단하게 구현하려 하는데요. 공지하기 API를 만들어서 각 유저별로 해당 공지사항을 전부 추가하는 방식을 고려하고 있습니다.
close #16

[Issue #16] 알림 목록 조회 및 확인 완료 처리 API

---

src/main/java/yapp/buddycon/common/exception/ErrorCode.java
src/main/java/yapp/buddycon/web/member/adapter/in/MemberController.java
src/main/java/yapp/buddycon/web/member/adapter/out/NotificationSettingJpaRepository.java
src/main/java/yapp/buddycon/web/member/adapter/out/NotificationSettingQueryRepository.java
src/main/java/yapp/buddycon/web/member/application/port/in/MemberUseCase.java
src/main/java/yapp/buddycon/web/member/application/port/out/NotificationSettingQueryPort.java
src/main/java/yapp/buddycon/web/member/application/service/MemberService.java

- 사용자 별 알림 설정 조회 API 추가
- `GET::/api/v1/member/notification-setting` API 추가
close #48

[Issue #48] 알림 설정 조회 API

---

src/main/java/yapp/buddycon/common/exception/ErrorCode.java
src/main/java/yapp/buddycon/common/util/AwsS3FileProvider.java
src/main/java/yapp/buddycon/web/coupon/adapter/in/CouponController.java
src/main/java/yapp/buddycon/web/coupon/adapter/in/request/CustomCouponCreationRequestDto.java
src/main/java/yapp/buddycon/web/coupon/application/port/in/CouponUseCase.java
src/main/java/yapp/buddycon/web/coupon/application/service/CouponService.java
src/main/java/yapp/buddycon/web/coupon/domain/CouponInfo.java

이미지와 함께 제작티콘 생성을 요청하는 API 추가
- `POST::/api/v1/coupon/custom-coupon` API 추가
- 빈 이미지 예외처리 시점 변경
close #50

[Issue #50] 제작티콘 추가 API

---

src/main/java/yapp/buddycon/web/coupon/adapter/in/response/CouponsResponseDto.java
src/main/java/yapp/buddycon/web/coupon/adapter/in/response/SharedCouponsResponseDto.java
src/main/java/yapp/buddycon/web/coupon/adapter/out/CouponJpaRepository.java
src/main/java/yapp/buddycon/web/coupon/adapter/out/SharedCouponJpaRepository.java

기프티콘, 제작티콘, 만든쿠폰 API response에 createdAt 추가
네트워크에 연결이 되어있지 않을 때 안드로이드 측에서 직접 정렬이 가능해야하기 때문에 
응답값에 createdAt을 추가하였습니다.
close #63

[Issue #63] 모든 정렬 조회 Response에 createdAt 추가

---

src/main/java/yapp/buddycon/web/member/adapter/in/MemberController.java
src/main/java/yapp/buddycon/web/member/adapter/in/response/NotificationSettingResponseDto.java
src/main/java/yapp/buddycon/web/member/adapter/out/NotificationSettingJpaRepository.java
src/main/java/yapp/buddycon/web/member/adapter/out/NotificationSettingQueryRepository.java
src/main/java/yapp/buddycon/web/member/application/port/in/MemberUseCase.java
src/main/java/yapp/buddycon/web/member/application/port/out/NotificationSettingQueryPort.java
src/main/java/yapp/buddycon/web/member/application/service/MemberService.java
src/main/java/yapp/buddycon/web/member/domain/NotificationSetting.java

유저 알림 설정 수정 API 추가
- 유저 알림 설정 조회 시 엔티티로 조회 후 ResponseDto로 파싱하도록 수정
- `patch::/api/v1/member/notification-setting` API 추가
close #52

52 feature 유저 알림 설정 수정 api

---

src/main/java/yapp/buddycon/common/exception/ErrorCode.java
src/main/java/yapp/buddycon/web/auth/application/service/AuthService.java
src/main/java/yapp/buddycon/web/member/adapter/in/MemberController.java
src/main/java/yapp/buddycon/web/member/application/port/in/MemberUseCase.java
src/main/java/yapp/buddycon/web/member/application/port/out/MemberQueryPort.java
src/main/java/yapp/buddycon/web/member/application/service/MemberService.java
src/main/java/yapp/buddycon/web/member/domain/Member.java

회원탈퇴 api 구현
회원탈퇴 api를 구현하였습니다.
회원 탈퇴에 따른 다른 도메인의 deleted처리는 추후 이슈를 파서 구현하도록 하겠습니다.
close #55

[Issue #55] 회원탈퇴 api

---

src/main/java/yapp/buddycon/web/coupon/adapter/in/SharedCouponController.java
src/main/java/yapp/buddycon/web/coupon/adapter/out/SharedCouponJpaRepository.java
src/main/java/yapp/buddycon/web/coupon/adapter/out/SharedCouponQueryRepository.java
src/main/java/yapp/buddycon/web/coupon/application/port/in/SharedCouponUseCase.java
src/main/java/yapp/buddycon/web/coupon/application/port/out/SharedCouponQueryPort.java
src/main/java/yapp/buddycon/web/coupon/application/service/SharedCouponService.java
src/main/java/yapp/buddycon/web/coupon/domain/SharedCoupon.java

만든 쿠폰 삭제 api 구현
만든 쿠폰 삭제 api 구현
만든 쿠폰 삭제 api를 soft delete로 구현함에 따라, '만든쿠폰 정렬'등의 다른 api에서 추가적인 리팩토링 작업이 필요합니다.
이는 추후 이슈를 파서 구현하도록 하겠습니다.
close #57

[Issue #57] 만든 쿠폰 삭제 api

---

src/main/java/yapp/buddycon/web/coupon/adapter/out/CouponJpaRepository.java
src/main/java/yapp/buddycon/web/coupon/adapter/out/CouponQueryRepository.java
src/main/java/yapp/buddycon/web/coupon/adapter/out/SharedCouponJpaRepository.java
src/main/java/yapp/buddycon/web/coupon/domain/SharedCoupon.java
src/main/java/yapp/buddycon/web/member/adapter/out/MemberJpaRepository.java
src/main/java/yapp/buddycon/web/member/adapter/out/MemberQueryRepository.java

엔티티를 soft-delete 방식으로 삭제함에 따라 관련 로직 수정
- 관련 엔티티 접근 시 항상 deleted 컬럼을 확인하도록 수정
- Member
- Coupon
- SharedCoupon
close #72

[Issue #72] soft-delete 관련 로직 수정

---

src/main/java/yapp/buddycon/web/coupon/adapter/in/request/CustomCouponCreationRequestDto.java
src/main/java/yapp/buddycon/web/coupon/adapter/in/request/GifticonCreationRequestDto.java
src/main/java/yapp/buddycon/web/coupon/adapter/out/SharedCouponQueryRepository.java
src/main/java/yapp/buddycon/web/coupon/application/port/out/CouponToSharedCouponQueryPort.java
src/main/java/yapp/buddycon/web/coupon/application/service/CouponService.java
src/main/java/yapp/buddycon/web/coupon/domain/SharedCoupon.java

쿠폰 등록 시 request dto에 sharedCouponId 추가
- 쿠폰 등록 request dto에 sharedCouponId 추가
- 등록 시 해당하는 SharedCoupon의 saved=true로 변경
close #76

[Issue #76] 쿠폰 등록 시 request dto에 sharedCouponId 추가

---

src/main/java/yapp/buddycon/web/coupon/application/service/SharedCouponService.java
src/main/java/yapp/buddycon/web/coupon/domain/Coupon.java
src/main/java/yapp/buddycon/web/coupon/domain/SharedCoupon.java

쿠폰 공유 완료 시 해당 쿠폰 공유 완료 처리
- 쿠폰 공유 완료 시 해당 쿠폰을 공유 완료 상태로 변경하도록 수정하였습니다.
- https://github.com/YAPP-Github/21st-Android-Team-1-BE/pull/80 PR 머지 후 머지 부탁드립니다~
close #79

[Issue #79] 쿠폰 공유 완료 시 해당 쿠폰 공유 완료 처리

---

src/main/java/yapp/buddycon/common/response/DefaultIdResponseDto.java
src/main/java/yapp/buddycon/web/coupon/adapter/in/SharedCouponController.java
src/main/java/yapp/buddycon/web/coupon/adapter/out/SharedCouponCommandRepository.java
src/main/java/yapp/buddycon/web/coupon/application/port/in/SharedCouponUseCase.java
src/main/java/yapp/buddycon/web/coupon/application/port/out/SharedCouponCommandPort.java
src/main/java/yapp/buddycon/web/coupon/application/service/SharedCouponService.java

만든쿠폰 생성 시 id 반환
- 관련 API
- POST::api/v1/coupon/share/gifticon
- POST::api/v1/coupon/share/custom-coupon
- DefaultIdResponseDto 추가
close #83

[Issue #83] 만든쿠폰 생성 시 id 반환
